services:
  redis:
    image: redis:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - '6379:6379'
    # volumes:
    #   - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
    #   - ./StirlingPDF/extraConfigs:/configs
    #   - ./StirlingPDF/customFiles:/customFiles/
    #   - ./StirlingPDF/logs:/logs/
    #   - ./StirlingPDF/pipeline:/pipeline/
    # environment:
    #   - DISABLE_ADDITIONAL_FEATURES=false
    #   - LANGS=en_GB
