name: docker-compose-actions-workflow
on:
  workflow_dispatch:
  # push:
  #   # Sequence of patterns matched against refs/tags
  #   tags:
  #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  #     - 'c*'

permissions:
    contents: write
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          curl https://aka.ms/TunnelsCliDownload/linux-x64 -L -J --output devtunnel


      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - run: |
          npm i -g concurrently
          
      - run: |
          cat <<EOF > server.js
          #!/bin/bash
          const http = require('http');
          
          const hostname = '127.0.0.1'; // Localhost
          const port = 3000; // Port to listen on
          
          const server = http.createServer((req, res) => {
            // Set the HTTP header for the response
            res.statusCode = 200;
            res.setHeader('Content-Type', 'text/plain');
          
            // Send the response body
            res.end('Hello World from Node.js!\n');
          });
          
          server.listen(port, hostname, () => {
            console.log(`Server running at http://${hostname}:${port}/`);
          });
          EOF
                
      - run: |
          sudo chmod -R +x . && \
          ./devtunnel user login -g -d
      
      - run: |
          concurrently "./devtunnel host -p 6379 3000 --allow-anonymous --protocol auto" "docker compose up --build" "node ./server.js"
      
    # # continue-on-error: true
    #   - name: set permission and run
    #     run: |
    #       sudo chmod -R +x . && \
    #       mkdir -p dist && \
    #       ls && \
    #       
          
      # - uses: fastai/workflows/ssh@master
      #   with:
      #     ssh_key: ${{ secrets.SSH_KEY }}
      #     key_file: id_ecdsa
          
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@master
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "dist"
          filename: "docker-compose-playground-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/docker-compose-playground-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
